### ISSUE TITLE
[models] Rename Field.help_text → Field.description

### ISSUE THREAD

**Issue by wo0dyn** [peopledoc/django-formidable#190]
Follow-up of #188 

## TODO

* [ ] Migration: `Field.help_text` → `Field.description` 
* [ ] Migration: `Item.help_text`  → `Item.description` 
* [ ] Make sure that schema already serialized are still working<sup>1</sup>

## Notes

1. Maybe implement a mapping, and raise a python warning to tell developers that the field won't be available soon

**Comment by brunobord** [comment]
I see that the schema migration mechanism is ready in the codebase but... I think there's something missing like:

* a way to easily run all the wanted migrations in order to upgrade the saved schemas from a version to the next one, and then eventually save them,
* a documentation on how to do it,
* integrate this migration mechanism in our internal (secret) projects, on-the-fly (would cost CPU, but would guarantee Blue/Green-like behaviour) or via a one-shot script (beware on how to keep it blue/green ?)

**Comment by brunobord** [comment]
isn't this already done with the JSON migrations?

**Comment by wo0dyn** [comment]
I think we should remove references such as: https://github.com/peopledoc/django-formidable/blob/e8f19dcaf10b22b4424b9e8a5903f1bd78fa7a33/formidable/serializers/fields.py#L78-L82

**Comment by brunobord** [comment]
yes, and it's part of https://github.com/peopledoc/django-formidable/issues/292

**Comment by brunobord** [comment]
my point was to say that the renaming has been completed, so I think we may close this one
